# Generated by Django 5.0.6 on 2024-05-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
