# Generated by Django 5.0.6 on 2024-05-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this LibraryUser belongs to.', related_name='LibraryUser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this LibraryUser.', related_name='LibraryUser_set', to='auth.permission', verbose_name='LibraryUser permissions'),
        ),
    ]
