# Generated by Django 5.0.6 on 2024-05-16 02:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_libraryuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+201234567891', max_length=128, null=True, region='EG'),
        ),
    ]
