# Generated by Django 5.0.6 on 2024-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_libraryuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='isAdmin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
